name: Import Crafting Interpreters into TeiA

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Clone Crafting Interpreters
        run: |
          git clone --depth 1 https://github.com/munificent/craftinginterpreters.git ci

      - name: Move clox VM into TeiA folder
        run: |
          mkdir -p TeiA
          rm -rf TeiA/clox

          cp -r ci/c TeiA/clox

      - name: Cleanup unnecessary files
        run: |
          rm -rf ci

      - name: Commit changes
        run: |
          git add TeiA

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Import clox VM into TeiA"
          git push
